const entries = [
  memory('behaviour.signal-editorial.impact-settle', 'behaviour', 'signal-editorial',
    '@cut3/agent-memory/behaviours/signal-editorial/EditorialImpactSettle',
    ['condensed headline impact', 'hard editorial media entrance'],
    ['signal red hard shadow', 'asymmetric slam', 'focus recoil']),
  memory('behaviour.signal-editorial.razor-cut-sweep', 'behaviour', 'signal-editorial',
    '@cut3/agent-memory/behaviours/signal-editorial/RazorCutSweep',
    ['short scene transition', 'diagonal editorial cut'],
    ['paper-black blade', 'signal-red blade', 'diagonal overshoot']),
  memory('behaviour.signal-editorial.ink-rule-strike', 'behaviour', 'signal-editorial',
    '@cut3/agent-memory/behaviours/signal-editorial/InkRuleStrike',
    ['headline underline', 'editorial annotation'],
    ['signal-red ink', 'cubic hand line', 'thick-to-thin strike']),
  memory('behaviour.signal-editorial.scene-reveal', 'behaviour', 'signal-editorial',
    '@cut3/agent-memory/behaviours/signal-editorial/SignalSceneReveal',
    ['incoming scene under razor transition'],
    ['covered-frame handoff', 'white focus landing', 'signal contrast settle']),
  memory('unit.signal-editorial.headline-band', 'unit', 'signal-editorial',
    '@cut3/agent-memory/units/signal-editorial/SignalHeadlineBand',
    ['social headline', 'quote title'],
    ['Barlow Condensed 800', 'paper black', 'signal red gutter']),
  memory('unit.signal-editorial.media-plate', 'unit', 'signal-editorial',
    '@cut3/agent-memory/units/signal-editorial/SignalMediaPlate',
    ['cropped photo', 'cropped video'],
    ['hard crop', 'registration cross', 'low saturation media']),
  memory('unit.signal-editorial.razor-transition', 'unit', 'signal-editorial',
    '@cut3/agent-memory/units/signal-editorial/SignalRazorTransition',
    ['transition between scenes'],
    ['three diagonal blades', 'paper and signal-red palette']),

  memory('behaviour.archival-dossier.pinned-evidence-drop', 'behaviour', 'archival-dossier',
    '@cut3/agent-memory/behaviours/archival-dossier/PinnedEvidenceDrop',
    ['photo evidence entrance', 'paper card entrance'],
    ['pin-first fall', 'three-stage rotation', 'heavy paper shadow']),
  memory('behaviour.archival-dossier.carbon-copy-cadence', 'behaviour', 'archival-dossier',
    '@cut3/agent-memory/behaviours/archival-dossier/CarbonCopyCadence',
    ['podcast quote reveal', 'transcript reveal'],
    ['uneven word cadence', 'IBM Plex Mono', 'carbon ink ghost']),
  memory('behaviour.archival-dossier.casefile-shutter-fall', 'behaviour', 'archival-dossier',
    '@cut3/agent-memory/behaviours/archival-dossier/CasefileShutterFall',
    ['documentary scene transition'],
    ['uneven shutter slats', 'paper black', 'oxide red recoil']),
  memory('behaviour.archival-dossier.scene-reveal', 'behaviour', 'archival-dossier',
    '@cut3/agent-memory/behaviours/archival-dossier/DossierSceneReveal',
    ['incoming scene under case-file shutter'],
    ['covered-frame handoff', 'darkroom development', 'desaturated paper landing']),
  memory('unit.archival-dossier.photo-mount', 'unit', 'archival-dossier',
    '@cut3/agent-memory/units/archival-dossier/DossierPhotoMount',
    ['documentary photo', 'archival video still'],
    ['torn tape path', 'evidence thread', 'warm paper mount']),
  memory('unit.archival-dossier.quote-strip', 'unit', 'archival-dossier',
    '@cut3/agent-memory/units/archival-dossier/DossierQuoteStrip',
    ['podcast quote', 'document excerpt'],
    ['carbon-copy mono', 'torn warm paper', 'oxide underline']),
  memory('unit.archival-dossier.shutter-transition', 'unit', 'archival-dossier',
    '@cut3/agent-memory/units/archival-dossier/CasefileShutterTransition',
    ['transition between documentary scenes'],
    ['four case-file slats', 'oxide interruption']),

  memory('behaviour.retro-ritual.ritual-card-deal', 'behaviour', 'retro-ritual',
    '@cut3/agent-memory/behaviours/retro-ritual/RitualCardDeal',
    ['ranking card entrance', 'ritual offer entrance'],
    ['integer-snapped deal', 'purple recoil', 'zero blur']),
  memory('behaviour.retro-ritual.bone-idle-hop', 'behaviour', 'retro-ritual',
    '@cut3/agent-memory/behaviours/retro-ritual/BoneIdleHop',
    ['idle card life', 'pixel relic idle'],
    ['held-frame sine hop', 'integer displacement', 'hard black shadow']),
  memory('behaviour.retro-ritual.portal-tile-stutter', 'behaviour', 'retro-ritual',
    '@cut3/agent-memory/behaviours/retro-ritual/PortalTileStutter',
    ['pixel scene transition'],
    ['four phase scale', 'soul-green flash', 'purple offset']),
  memory('behaviour.retro-ritual.rune-trace', 'behaviour', 'retro-ritual',
    '@cut3/agent-memory/behaviours/retro-ritual/RuneTrace',
    ['rune drawing', 'pixel annotation'],
    ['held drawing increments', 'soul-green stroke', 'square line caps']),
  memory('behaviour.retro-ritual.portal-scene-reveal', 'behaviour', 'retro-ritual',
    '@cut3/agent-memory/behaviours/retro-ritual/PortalSceneReveal',
    ['incoming scene under portal mosaic'],
    ['covered-frame handoff', 'four held reveal steps', 'green-purple flash settle']),
  memory('unit.retro-ritual.offer-card', 'unit', 'retro-ritual',
    '@cut3/agent-memory/units/retro-ritual/RitualOfferCard',
    ['ranking item', 'ritual option'],
    ['bone frame', 'soul-green bar', 'pixel rune']),
  memory('unit.retro-ritual.portal-tile-transition', 'unit', 'retro-ritual',
    '@cut3/agent-memory/units/retro-ritual/PortalTileTransition',
    ['transition to ranking winner'],
    ['six-by-ten mosaic', 'hard pixel border', 'green-purple checker']),

  memory('behaviour.blue-terminal.message-cadence', 'behaviour', 'blue-terminal',
    '@cut3/agent-memory/behaviours/blue-terminal/TerminalMessageCadence',
    ['pixel system message reveal', 'pixel terminal dialogue cadence'],
    ['uneven pixel typing', 'held block cursor', 'cobalt phosphor echo']),
  memory('behaviour.blue-terminal.panel-boot', 'behaviour', 'blue-terminal',
    '@cut3/agent-memory/behaviours/blue-terminal/TerminalPanelBoot',
    ['terminal panel entrance', 'system message boot'],
    ['stepped cobalt scale', 'ice flash', 'deep terminal settle']),
  memory('unit.blue-terminal.message-panel', 'unit', 'blue-terminal',
    '@cut3/agent-memory/units/blue-terminal/BlueTerminalMessagePanel',
    ['pixel system message', 'pixel terminal dialogue panel'],
    ['cobalt layered frame', 'pixel status rail', 'ice border', 'Press Start 2P 400']),

  memory('behaviour.neon-heart-pop.chroma-pop-settle', 'behaviour', 'neon-heart-pop',
    '@cut3/agent-memory/behaviours/neon-heart-pop/ChromaPopSettle',
    ['neon nameplate entrance', 'pop title landing'],
    ['zero-to-overshoot scale', 'chromatic recoil', 'hot-pink glow settle']),
  memory('unit.neon-heart-pop.chroma-nameplate', 'unit', 'neon-heart-pop',
    '@cut3/agent-memory/units/neon-heart-pop/NeonChromaNameplate',
    ['two-line neon nameplate', 'heart-pop title'],
    ['cyan-red chromatic ghosts', 'hot-pink heart', 'Bebas Neue 400', 'Caveat 700']),

  memory('behaviour.fight-zine.row-stagger', 'behaviour', 'fight-zine',
    '@cut3/agent-memory/behaviours/fight-zine/ZineRowStagger',
    ['text ranking row entrance', 'fight-stat strip reveal'],
    ['hard lateral throw', 'paper overshoot', 'marker settle']),
  memory('behaviour.fight-zine.boiling-ink', 'behaviour', 'fight-zine',
    '@cut3/agent-memory/behaviours/fight-zine/BoilingInk',
    ['inked ranking idle', 'zine card texture'],
    ['two-frame hold', 'deterministic jitter', 'additive ink motion']),
  memory('unit.fight-zine.rank-row', 'unit', 'fight-zine',
    '@cut3/agent-memory/units/fight-zine/FightZineRankRow',
    ['text ranking row', 'fight-stat strip'],
    ['cream paper', 'yellow tape', 'rough ink rule', 'Anton 400', 'Permanent Marker 400']),

];

export const memoryCatalog = Object.freeze(entries);

export function findMemories({ style, purpose, type } = {}) {
  return memoryCatalog.filter((entry) => (
    (style === undefined || entry.style === style)
    && (type === undefined || entry.type === type)
    && (purpose === undefined || entry.useWhen.includes(purpose))
  ));
}

function memory(id, type, style, importPath, useWhen, preserves) {
  return Object.freeze({
    id,
    import: importPath,
    preserves: Object.freeze(preserves),
    style,
    type,
    useWhen: Object.freeze(useWhen),
  });
}
