const entries = [
  memory('behaviour.signal-editorial.impact-settle', 'behaviour', 'signal-editorial',
    '@cut3/agent-memory/behaviours/signal-editorial/EditorialImpactSettle',
    ['condensed headline impact', 'hard editorial media entrance'],
    ['signal red hard shadow', 'asymmetric slam', 'focus recoil']),
  memory('behaviour.signal-editorial.razor-cut-sweep', 'behaviour', 'signal-editorial',
    '@cut3/agent-memory/behaviours/signal-editorial/RazorCutSweep',
    ['short scene transition', 'diagonal editorial cut'],
    ['paper-black blade', 'signal-red blade', 'diagonal overshoot']),
  memory('behaviour.signal-editorial.ink-rule-strike', 'behaviour', 'signal-editorial',
    '@cut3/agent-memory/behaviours/signal-editorial/InkRuleStrike',
    ['headline underline', 'editorial annotation'],
    ['signal-red ink', 'cubic hand line', 'thick-to-thin strike']),
  memory('behaviour.signal-editorial.scene-reveal', 'behaviour', 'signal-editorial',
    '@cut3/agent-memory/behaviours/signal-editorial/SignalSceneReveal',
    ['incoming scene under razor transition'],
    ['covered-frame handoff', 'white focus landing', 'signal contrast settle']),
  memory('unit.signal-editorial.headline-band', 'unit', 'signal-editorial',
    '@cut3/agent-memory/units/signal-editorial/SignalHeadlineBand',
    ['social headline', 'quote title'],
    ['Barlow Condensed 800', 'paper black', 'signal red gutter']),
  memory('unit.signal-editorial.media-plate', 'unit', 'signal-editorial',
    '@cut3/agent-memory/units/signal-editorial/SignalMediaPlate',
    ['cropped photo', 'cropped video'],
    ['hard crop', 'registration cross', 'low saturation media']),
  memory('unit.signal-editorial.razor-transition', 'unit', 'signal-editorial',
    '@cut3/agent-memory/units/signal-editorial/SignalRazorTransition',
    ['transition between scenes'],
    ['three diagonal blades', 'paper and signal-red palette']),

  memory('behaviour.archival-dossier.pinned-evidence-drop', 'behaviour', 'archival-dossier',
    '@cut3/agent-memory/behaviours/archival-dossier/PinnedEvidenceDrop',
    ['photo evidence entrance', 'paper card entrance'],
    ['pin-first fall', 'three-stage rotation', 'heavy paper shadow']),
  memory('behaviour.archival-dossier.carbon-copy-cadence', 'behaviour', 'archival-dossier',
    '@cut3/agent-memory/behaviours/archival-dossier/CarbonCopyCadence',
    ['podcast quote reveal', 'transcript reveal'],
    ['uneven word cadence', 'IBM Plex Mono', 'carbon ink ghost']),
  memory('behaviour.archival-dossier.casefile-shutter-fall', 'behaviour', 'archival-dossier',
    '@cut3/agent-memory/behaviours/archival-dossier/CasefileShutterFall',
    ['documentary scene transition'],
    ['uneven shutter slats', 'paper black', 'oxide red recoil']),
  memory('behaviour.archival-dossier.scene-reveal', 'behaviour', 'archival-dossier',
    '@cut3/agent-memory/behaviours/archival-dossier/DossierSceneReveal',
    ['incoming scene under case-file shutter'],
    ['covered-frame handoff', 'darkroom development', 'desaturated paper landing']),
  memory('unit.archival-dossier.photo-mount', 'unit', 'archival-dossier',
    '@cut3/agent-memory/units/archival-dossier/DossierPhotoMount',
    ['documentary photo', 'archival video still'],
    ['torn tape path', 'evidence thread', 'warm paper mount']),
  memory('unit.archival-dossier.quote-strip', 'unit', 'archival-dossier',
    '@cut3/agent-memory/units/archival-dossier/DossierQuoteStrip',
    ['podcast quote', 'document excerpt'],
    ['carbon-copy mono', 'torn warm paper', 'oxide underline']),
  memory('unit.archival-dossier.shutter-transition', 'unit', 'archival-dossier',
    '@cut3/agent-memory/units/archival-dossier/CasefileShutterTransition',
    ['transition between documentary scenes'],
    ['four case-file slats', 'oxide interruption']),

  memory('behaviour.retro-ritual.ritual-card-deal', 'behaviour', 'retro-ritual',
    '@cut3/agent-memory/behaviours/retro-ritual/RitualCardDeal',
    ['ranking card entrance', 'ritual offer entrance'],
    ['integer-snapped deal', 'purple recoil', 'zero blur']),
  memory('behaviour.retro-ritual.bone-idle-hop', 'behaviour', 'retro-ritual',
    '@cut3/agent-memory/behaviours/retro-ritual/BoneIdleHop',
    ['idle card life', 'pixel relic idle'],
    ['held-frame sine hop', 'integer displacement', 'hard black shadow']),
  memory('behaviour.retro-ritual.portal-tile-stutter', 'behaviour', 'retro-ritual',
    '@cut3/agent-memory/behaviours/retro-ritual/PortalTileStutter',
    ['pixel scene transition'],
    ['four phase scale', 'soul-green flash', 'purple offset']),
  memory('behaviour.retro-ritual.rune-trace', 'behaviour', 'retro-ritual',
    '@cut3/agent-memory/behaviours/retro-ritual/RuneTrace',
    ['rune drawing', 'pixel annotation'],
    ['held drawing increments', 'soul-green stroke', 'square line caps']),
  memory('behaviour.retro-ritual.portal-scene-reveal', 'behaviour', 'retro-ritual',
    '@cut3/agent-memory/behaviours/retro-ritual/PortalSceneReveal',
    ['incoming scene under portal mosaic'],
    ['covered-frame handoff', 'four held reveal steps', 'green-purple flash settle']),
  memory('unit.retro-ritual.offer-card', 'unit', 'retro-ritual',
    '@cut3/agent-memory/units/retro-ritual/RitualOfferCard',
    ['ranking item', 'ritual option'],
    ['bone frame', 'soul-green bar', 'pixel rune']),
  memory('unit.retro-ritual.portal-tile-transition', 'unit', 'retro-ritual',
    '@cut3/agent-memory/units/retro-ritual/PortalTileTransition',
    ['transition to ranking winner'],
    ['six-by-ten mosaic', 'hard pixel border', 'green-purple checker']),

  memory('unit.composition.signal-editorial', 'composition', 'signal-editorial',
    '@cut3/agent-memory/compositions/SignalEditorialComposition',
    ['vertical social opener'],
    ['media plate', 'headline band', 'razor transition']),
  memory('unit.composition.archival-dossier', 'composition', 'archival-dossier',
    '@cut3/agent-memory/compositions/ArchivalDossierComposition',
    ['podcast quote video', 'documentary excerpt'],
    ['photo evidence', 'carbon transcript', 'casefile shutter']),
  memory('unit.composition.retro-ritual-ranking', 'composition', 'retro-ritual',
    '@cut3/agent-memory/compositions/RetroRitualRankingComposition',
    ['ranking video', 'list reveal'],
    ['arbitrary card count', 'ritual cards', 'portal winner cut']),
];

export const memoryCatalog = Object.freeze(entries);

export function findMemories({ style, purpose, type } = {}) {
  return memoryCatalog.filter((entry) => (
    (style === undefined || entry.style === style)
    && (type === undefined || entry.type === type)
    && (purpose === undefined || entry.useWhen.includes(purpose))
  ));
}

function memory(id, type, style, importPath, useWhen, preserves) {
  return Object.freeze({
    id,
    import: importPath,
    preserves: Object.freeze(preserves),
    style,
    type,
    useWhen: Object.freeze(useWhen),
  });
}
