const entries = [
  memory('behaviour.signal-editorial.impact-settle', 'behaviour', 'signal-editorial',
    '@cut3/agent-memory/behaviours/signal-editorial/EditorialImpactSettle',
    ['condensed headline impact', 'hard editorial media entrance'],
    ['signal red hard shadow', 'asymmetric slam', 'focus recoil']),
  memory('behaviour.signal-editorial.razor-cut-sweep', 'behaviour', 'signal-editorial',
    '@cut3/agent-memory/behaviours/signal-editorial/RazorCutSweep',
    ['short scene transition', 'diagonal editorial cut'],
    ['paper-black blade', 'signal-red blade', 'diagonal overshoot']),
  memory('behaviour.signal-editorial.ink-rule-strike', 'behaviour', 'signal-editorial',
    '@cut3/agent-memory/behaviours/signal-editorial/InkRuleStrike',
    ['headline underline', 'editorial annotation'],
    ['signal-red ink', 'cubic hand line', 'thick-to-thin strike']),
  memory('behaviour.signal-editorial.scene-reveal', 'behaviour', 'signal-editorial',
    '@cut3/agent-memory/behaviours/signal-editorial/SignalSceneReveal',
    ['incoming scene under razor transition'],
    ['covered-frame handoff', 'white focus landing', 'signal contrast settle']),
  memory('unit.signal-editorial.headline-band', 'unit', 'signal-editorial',
    '@cut3/agent-memory/units/signal-editorial/SignalHeadlineBand',
    ['social headline', 'quote title'],
    ['Barlow Condensed 800', 'paper black', 'signal red gutter']),
  memory('unit.signal-editorial.media-plate', 'unit', 'signal-editorial',
    '@cut3/agent-memory/units/signal-editorial/SignalMediaPlate',
    ['cropped photo', 'cropped video'],
    ['hard crop', 'registration cross', 'low saturation media']),
  memory('unit.signal-editorial.razor-transition', 'unit', 'signal-editorial',
    '@cut3/agent-memory/units/signal-editorial/SignalRazorTransition',
    ['transition between scenes'],
    ['three diagonal blades', 'paper and signal-red palette']),

  memory('behaviour.archival-dossier.pinned-evidence-drop', 'behaviour', 'archival-dossier',
    '@cut3/agent-memory/behaviours/archival-dossier/PinnedEvidenceDrop',
    ['photo evidence entrance', 'paper card entrance'],
    ['pin-first fall', 'three-stage rotation', 'heavy paper shadow']),
  memory('behaviour.archival-dossier.carbon-copy-cadence', 'behaviour', 'archival-dossier',
    '@cut3/agent-memory/behaviours/archival-dossier/CarbonCopyCadence',
    ['podcast quote reveal', 'transcript reveal'],
    ['uneven word cadence', 'IBM Plex Mono', 'carbon ink ghost']),
  memory('behaviour.archival-dossier.casefile-shutter-fall', 'behaviour', 'archival-dossier',
    '@cut3/agent-memory/behaviours/archival-dossier/CasefileShutterFall',
    ['documentary scene transition'],
    ['uneven shutter slats', 'paper black', 'oxide red recoil']),
  memory('behaviour.archival-dossier.scene-reveal', 'behaviour', 'archival-dossier',
    '@cut3/agent-memory/behaviours/archival-dossier/DossierSceneReveal',
    ['incoming scene under case-file shutter'],
    ['covered-frame handoff', 'darkroom development', 'desaturated paper landing']),
  memory('unit.archival-dossier.photo-mount', 'unit', 'archival-dossier',
    '@cut3/agent-memory/units/archival-dossier/DossierPhotoMount',
    ['documentary photo', 'archival video still', 'photo with handwritten date stamp'],
    ['torn tape path', 'evidence thread', 'warm paper mount', 'optional Caveat date stamp']),
  memory('unit.archival-dossier.quote-strip', 'unit', 'archival-dossier',
    '@cut3/agent-memory/units/archival-dossier/DossierQuoteStrip',
    ['podcast quote', 'document excerpt'],
    ['carbon-copy mono', 'torn warm paper', 'oxide underline']),
  memory('unit.archival-dossier.shutter-transition', 'unit', 'archival-dossier',
    '@cut3/agent-memory/units/archival-dossier/CasefileShutterTransition',
    ['transition between documentary scenes'],
    ['four case-file slats', 'oxide interruption']),

  memory('behaviour.retro-ritual.ritual-card-deal', 'behaviour', 'retro-ritual',
    '@cut3/agent-memory/behaviours/retro-ritual/RitualCardDeal',
    ['ranking card entrance', 'ritual offer entrance'],
    ['integer-snapped deal', 'purple recoil', 'zero blur']),
  memory('behaviour.retro-ritual.bone-idle-hop', 'behaviour', 'retro-ritual',
    '@cut3/agent-memory/behaviours/retro-ritual/BoneIdleHop',
    ['idle card life', 'pixel relic idle'],
    ['held-frame sine hop', 'integer displacement', 'hard black shadow']),
  memory('behaviour.retro-ritual.portal-tile-stutter', 'behaviour', 'retro-ritual',
    '@cut3/agent-memory/behaviours/retro-ritual/PortalTileStutter',
    ['pixel scene transition'],
    ['four phase scale', 'soul-green flash', 'purple offset']),
  memory('behaviour.retro-ritual.rune-trace', 'behaviour', 'retro-ritual',
    '@cut3/agent-memory/behaviours/retro-ritual/RuneTrace',
    ['rune drawing', 'pixel annotation'],
    ['held drawing increments', 'soul-green stroke', 'square line caps']),
  memory('behaviour.retro-ritual.portal-scene-reveal', 'behaviour', 'retro-ritual',
    '@cut3/agent-memory/behaviours/retro-ritual/PortalSceneReveal',
    ['incoming scene under portal mosaic'],
    ['covered-frame handoff', 'four held reveal steps', 'green-purple flash settle']),
  memory('unit.retro-ritual.offer-card', 'unit', 'retro-ritual',
    '@cut3/agent-memory/units/retro-ritual/RitualOfferCard',
    ['ranking item', 'ritual option'],
    ['bone frame', 'soul-green bar', 'pixel rune']),
  memory('unit.retro-ritual.portal-tile-transition', 'unit', 'retro-ritual',
    '@cut3/agent-memory/units/retro-ritual/PortalTileTransition',
    ['transition to ranking winner'],
    ['six-by-ten mosaic', 'hard pixel border', 'green-purple checker']),

  memory('behaviour.blue-terminal.message-cadence', 'behaviour', 'blue-terminal',
    '@cut3/agent-memory/behaviours/blue-terminal/TerminalMessageCadence',
    ['pixel system message reveal', 'pixel terminal dialogue cadence'],
    ['uneven pixel typing', 'held block cursor', 'cobalt phosphor echo']),
  memory('behaviour.blue-terminal.panel-boot', 'behaviour', 'blue-terminal',
    '@cut3/agent-memory/behaviours/blue-terminal/TerminalPanelBoot',
    ['terminal panel entrance', 'system message boot'],
    ['stepped cobalt scale', 'ice flash', 'deep terminal settle']),
  memory('unit.blue-terminal.message-panel', 'unit', 'blue-terminal',
    '@cut3/agent-memory/units/blue-terminal/BlueTerminalMessagePanel',
    ['pixel system message', 'pixel terminal dialogue panel'],
    ['cobalt layered frame', 'pixel status rail', 'ice border', 'Press Start 2P 400']),

  memory('behaviour.neon-heart-pop.chroma-pop-settle', 'behaviour', 'neon-heart-pop',
    '@cut3/agent-memory/behaviours/neon-heart-pop/ChromaPopSettle',
    ['neon nameplate entrance', 'pop title landing'],
    ['zero-to-overshoot scale', 'chromatic recoil', 'hot-pink glow settle']),
  memory('unit.neon-heart-pop.chroma-nameplate', 'unit', 'neon-heart-pop',
    '@cut3/agent-memory/units/neon-heart-pop/NeonChromaNameplate',
    ['two-line neon nameplate', 'heart-pop title'],
    ['cyan-red chromatic ghosts', 'hot-pink heart', 'Bebas Neue 400', 'Caveat 700']),

  memory('behaviour.fight-zine.row-stagger', 'behaviour', 'fight-zine',
    '@cut3/agent-memory/behaviours/fight-zine/ZineRowStagger',
    ['text ranking row entrance', 'fight-stat strip reveal'],
    ['hard lateral throw', 'paper overshoot', 'marker settle']),
  memory('behaviour.fight-zine.boiling-ink', 'behaviour', 'fight-zine',
    '@cut3/agent-memory/behaviours/fight-zine/BoilingInk',
    ['inked ranking idle', 'zine card texture'],
    ['two-frame hold', 'deterministic jitter', 'additive ink motion']),
  memory('unit.fight-zine.rank-row', 'unit', 'fight-zine',
    '@cut3/agent-memory/units/fight-zine/FightZineRankRow',
    ['text ranking row', 'fight-stat strip'],
    ['cream paper', 'yellow tape', 'rough ink rule', 'Anton 400', 'Permanent Marker 400']),

  ...familyMemories('fight-zine', [
    ['behaviour.fight-zine.chart-cadence', 'behaviour',
      'behaviours/fight-zine/FightZineChartCadence',
      ['fight-stat chart entrance', 'zine counter board'],
      ['authored axis and stroke timings', 'counter spring cues', 'half-second exit']],
    ['behaviour.fight-zine.fight-night-shutter-hit', 'behaviour',
      'behaviours/fight-zine/FightNightShutterHit',
      ['media-rank flash hit', 'fight-night photo handoff'],
      ['variant-specific flash frames', 'saturation and blend coordination', 'semantic media plate owner']],
    ['behaviour.fight-zine.marker-scrawl-trace', 'behaviour',
      'behaviours/fight-zine/MarkerScrawlTrace',
      ['zine title marker stroke', 'hand-drawn annotation'],
      ['two authored trace windows', 'typed vector path progress', 'marker recoil']],
    ['behaviour.fight-zine.media-rank-cadence', 'behaviour',
      'behaviours/fight-zine/MediaRankCadence',
      ['ranked fight media card', 'fighter reveal sequence'],
      ['stamp/label/name spring schedule', 'media segment selection', 'Ken Burns exit']],
    ['behaviour.fight-zine.ranking-table-cadence', 'behaviour',
      'behaviours/fight-zine/RankingTableCadence',
      ['fight ranking table', 'scored zine leaderboard'],
      ['row spring stagger', 'score tick and badge pop', 'boiling-ink exit']],
    ['behaviour.fight-zine.title-cadence', 'behaviour',
      'behaviours/fight-zine/FightZineTitleCadence',
      ['fight-zine title card', 'boiling rank headline'],
      ['two-frame ink boil', 'border reveal', 'per-word spring cadence']],
    ['unit.fight-zine.chart', 'unit',
      'units/fight-zine/FightZineChart',
      ['fight-stat chart', 'zine score comparison'],
      ['typed vector axes and strokes', 'cream/ink/yellow palette', 'runtime counters']],
    ['unit.fight-zine.media-image', 'unit',
      'units/fight-zine/MediaRankPlate',
      ['fight-rank media crop', 'zine fighter image'],
      ['runtime Image role', 'authored grade stack', 'semantic media identity']],
    ['unit.fight-zine.media-rank-plate', 'unit',
      'units/fight-zine/MediaRankPlate',
      ['fighter media ranking', 'fight-night reveal card'],
      ['runtime Image and Audio slots', 'stamp/label/name hierarchy', 'SVG rays and flash layers']],
    ['unit.fight-zine.ranking-table', 'unit',
      'units/fight-zine/FightZineRankingTable',
      ['fight ranking table', 'zine leaderboard'],
      ['runtime ranks/names/scores', 'outlined type roles', 'score badge topology']],
    ['unit.fight-zine.score-badge', 'unit',
      'units/fight-zine/FightZineRankingTable',
      ['ranking score badge', 'fight-table point marker'],
      ['semantic badge role', 'yellow tape field', 'runtime score copy']],
    ['unit.fight-zine.score-counter', 'unit',
      'units/fight-zine/FightZineRankingTable',
      ['animated fight score', 'ranking counter'],
      ['semantic counter role', 'runtime numeric copy', 'authored tick cadence target']],
    ['unit.fight-zine.title', 'unit',
      'units/fight-zine/FightZineTitle',
      ['fight-zine headline', 'boiling ranking title'],
      ['runtime word roles', 'outlined Anton typography', 'cream-paper field']],
    ['unit.fight-zine.title-word', 'unit',
      'units/fight-zine/FightZineTitle',
      ['individual fight-title word', 'staggered zine headline token'],
      ['semantic word index', 'outlined display type', 'boiling-ink target']],
  ]),

  ...familyMemories('blue-terminal', [
    ['behaviour.blue-terminal.cursor-cadence', 'behaviour',
      'behaviours/blue-terminal/TerminalCursorCadence',
      ['terminal cursor timing', 'message-panel typing feedback'],
      ['authored blink periods', 'variant-specific cursor visibility']],
    ['behaviour.blue-terminal.indicator-cadence', 'behaviour',
      'behaviours/blue-terminal/TerminalIndicatorCadence',
      ['terminal status indicator', 'panel activity feedback'],
      ['held activity phases', 'cobalt-to-ice indicator cadence']],
    ['behaviour.blue-terminal.panel-transit', 'behaviour',
      'behaviours/blue-terminal/TerminalPanelTransit',
      ['terminal panel entrance and exit', 'message-system transition'],
      ['variant-specific slide and scale', 'coordinated opacity envelope']],
    ['behaviour.blue-terminal.scanline-cadence', 'behaviour',
      'behaviours/blue-terminal/TerminalScanlineCadence',
      ['CRT panel scan motion', 'terminal phosphor texture'],
      ['authored sine scan', 'held scanline phases']],
    ['behaviour.blue-terminal.text-cadence', 'behaviour',
      'behaviours/blue-terminal/TerminalTextCadence',
      ['terminal dialogue reveal', 'system-message typing'],
      ['variant-specific characters per second', 'owner-local runtime text mutation']],
    ['unit.blue-terminal.crt-panel', 'unit',
      'units/blue-terminal/TerminalCrtPanel',
      ['pixel CRT message', 'terminal system card'],
      ['Press Start 2P role', 'layered cobalt bevel', 'scanline field']],
    ['unit.blue-terminal.cursor', 'unit',
      'units/blue-terminal/TerminalAffordances',
      ['terminal block cursor', 'typed-message affordance'],
      ['semantic cursor role', 'cobalt phosphor palette']],
    ['unit.blue-terminal.indicator', 'unit',
      'units/blue-terminal/TerminalAffordances',
      ['terminal status light', 'message-state affordance'],
      ['semantic indicator role', 'held activity states']],
    ['unit.blue-terminal.scanline-field', 'unit',
      'units/blue-terminal/TerminalScanlineField',
      ['CRT surface treatment', 'terminal display texture'],
      ['authored scanline spacing', 'deep-navy phosphor field']],
    ['unit.blue-terminal.speaker-panel', 'unit',
      'units/blue-terminal/TerminalSpeakerPanel',
      ['speaker-labelled dialogue', 'soft terminal message'],
      ['Nunito 800/900 roles', 'speaker rail', 'pixel tail']],
    ['unit.blue-terminal.status-panel', 'unit',
      'units/blue-terminal/TerminalStatusPanel',
      ['tagged status message', 'terminal state notice'],
      ['Nunito role hierarchy', 'layered steel-blue frame', 'status rail']],
  ]),

  ...familyMemories('crt-glitch', [
    ['behaviour.crt-glitch.analog-scan-burst', 'behaviour',
      'behaviours/crt-glitch/AnalogScanBurst',
      ['procedural CRT field', 'canvas title glitch'],
      ['seeded grain and flicker', 'scanline and vignette cadence', 'RGB title split']],
    ['unit.crt-glitch.field', 'unit',
      'units/crt-glitch/CrtGlitchField',
      ['film-grain field', 'canvas glitch title'],
      ['plain projected frame state', 'direct native 2D draw method', 'semantic signal surface']],
    ['unit.crt-glitch.signal', 'unit',
      'units/crt-glitch/CrtGlitchField',
      ['raw CRT signal surface', 'canvas-drawn glitch source'],
      ['seeded film-grain and glitch-title variants', 'native canvas-2d draw method', 'owned by CrtGlitchField']],
  ]),

  ...familyMemories('flash-photo', [
    ['behaviour.flash-photo.exposure-bloom', 'behaviour',
      'behaviours/flash-photo/ExposureBloom',
      ['camera exposure hit', 'photo-shutter handoff'],
      ['authored 60/80ms windows', 'coordinated flash and grade envelope']],
    ['behaviour.flash-photo.shutter-flash-reframe', 'behaviour',
      'behaviours/flash-photo/ShutterFlashReframe',
      ['rapid photo sequence', 'multi-source shutter montage'],
      ['hard source schedule', 'crop and camera reframe', 'owner-local canvas recipe']],
    ['unit.flash-photo.canvas-frame', 'unit',
      'units/flash-photo/FlashPhotoPlate',
      ['canvas-authored photo frame', 'procedural shutter treatment'],
      ['plain projected frame state', 'direct native image draw', 'host-owned resource']],
    ['unit.flash-photo.exposure-plate', 'unit',
      'units/flash-photo/FlashPhotoPlate',
      ['shutter exposure layer', 'camera flash field'],
      ['semantic exposure channel', 'authored white-flash topology']],
    ['unit.flash-photo.frame', 'unit',
      'units/flash-photo/FlashPhotoPlate',
      ['active photo slot', 'shutter crop frame'],
      ['runtime Image ownership', 'cover crop and reframe', 'hard source visibility']],
    ['unit.flash-photo.grade-plate', 'unit',
      'units/flash-photo/FlashPhotoPlate',
      ['photo grade handoff', 'shutter colour treatment'],
      ['semantic grade channel', 'ordered authored filter stack']],
    ['unit.flash-photo.plate', 'unit',
      'units/flash-photo/FlashPhotoPlate',
      ['multi-source photo shutter', 'flash-photo montage'],
      ['one-to-five runtime images', 'named animation channels', 'black-field composition']],
    ['unit.flash-photo.texture', 'unit',
      'units/flash-photo/FlashPhotoPlate',
      ['photo scanline texture', 'shutter surface distress'],
      ['static DOM stripe texture', 'authored scanline density']],
  ]),

  ...familyMemories('impact', [
    ['behaviour.impact.cut-cadence', 'behaviour',
      'behaviours/impact/ImpactCutCadence',
      ['impact freeze cut', 'photo or type depth punch'],
      ['recipe-and-role closed binding', 'coordinated pose/grade/presence', 'authored frame windows']],
    ['unit.impact.cut-stage', 'unit',
      'units/impact/ImpactCutStage',
      ['impact-family full-frame stage', 'freeze-frame punch composition'],
      ['semantic recipe identity', 'closed cadence bindings', 'black-field authored topology']],
    ['unit.impact.collage-depth-outline', 'unit',
      'units/impact/ImpactRecipeUnits',
      ['outlined photo collage', 'depth-punched media caption'],
      ['three runtime Image layers', 'outlined Impact caption', '3D collage geometry']],
    ['unit.impact.photo-chroma-depth', 'unit',
      'units/impact/ImpactRecipeUnits',
      ['chromatic photo depth hit', 'RGB freeze caption'],
      ['runtime Image and Text', 'red/cyan depth ghosts', 'perspective photo punch']],
    ['unit.impact.photo-depth-zoom', 'unit',
      'units/impact/ImpactRecipeUnits',
      ['depth-zoom photo hit', 'perspective freeze frame'],
      ['two runtime Image layers', 'translateZ depth stack', 'caption landing']],
    ['unit.impact.photo-punch-2d', 'unit',
      'units/impact/ImpactRecipeUnits',
      ['2D photo punch', 'impact freeze card'],
      ['runtime Image and Text', 'authored camera scale', 'hard grade and flash windows']],
    ['unit.impact.photo-screen-blend', 'unit',
      'units/impact/ImpactRecipeUnits',
      ['screen-blended photo hit', 'two-part impact caption'],
      ['runtime media layer', 'screen blend topology', 'coordinated caption roles']],
    ['unit.impact.photo-shadow-punch', 'unit',
      'units/impact/ImpactRecipeUnits',
      ['shadowed photo punch', 'graded impact still'],
      ['runtime Image role', 'ordered drop-shadow chain', '2D freeze cadence']],
    ['unit.impact.solid-card-depth', 'unit',
      'units/impact/ImpactRecipeUnits',
      ['solid depth card', 'geometry-only impact cut'],
      ['content-box cube geometry', 'authored borders', 'perspective card rotation']],
    ['unit.impact.triptych-depth', 'unit',
      'units/impact/ImpactRecipeUnits',
      ['three-panel depth photo', 'impact triptych'],
      ['three runtime Image layers', 'per-panel depth offsets', 'shared punch cadence']],
    ['unit.impact.type-collage-depth', 'unit',
      'units/impact/ImpactRecipeUnits',
      ['two-part type collage', 'layered depth headline'],
      ['runtime primary/secondary Text', 'conditional chroma bars', 'perspective type field']],
    ['unit.impact.type-depth-panel', 'unit',
      'units/impact/ImpactRecipeUnits',
      ['deep type panel', 'stacked Impact word field'],
      ['thirty runtime text layers', 'depth-distributed copies', 'panel perspective']],
    ['unit.impact.type-depth-rise', 'unit',
      'units/impact/ImpactRecipeUnits',
      ['rising depth headline', 'Impact type tunnel'],
      ['twenty runtime text layers', 'translateZ progression', 'authored entrance curve']],
    ['unit.impact.type-depth-stack', 'unit',
      'units/impact/ImpactRecipeUnits',
      ['stacked depth word', 'layered Impact headline'],
      ['twenty runtime text copies', 'perspective depth spacing', 'conditional flash topology']],
    ['unit.impact.type-depth-stamp', 'unit',
      'units/impact/ImpactRecipeUnits',
      ['depth-stamped word', 'layered type impact'],
      ['fifteen runtime text copies', 'authored depth stamp', 'periodic jitter window']],
    ['unit.impact.type-depth-tilt', 'unit',
      'units/impact/ImpactRecipeUnits',
      ['tilted depth headline', 'perspective type hit'],
      ['twenty-five runtime text copies', 'rotateX/Y depth field', 'hard landing window']],
  ]),

  ...familyMemories('kinetic-intertitles', [
    ['behaviour.kinetic-intertitles.impact-letter-cadence', 'behaviour',
      'behaviours/kinetic-intertitles/ImpactLetterCadence',
      ['per-letter impact reveal', 'scanline caption entrance'],
      ['staggered spring law', 'breathing scale', 'red shadow settle']],
    ['behaviour.kinetic-intertitles.impact-scanline-sweep', 'behaviour',
      'behaviours/kinetic-intertitles/ImpactScanlineSweep',
      ['impact caption scanline', 'deterministic title flicker'],
      ['five-frame flicker cadence', 'brightness pulse', 'typed violet-white sweep']],
    ['behaviour.kinetic-intertitles.progress-trace', 'behaviour',
      'behaviours/kinetic-intertitles/ProgressTrace',
      ['intertitle progress mark', 'serif underline trace'],
      ['closed vector path', 'authored spring trace', 'hold-and-fade envelope']],
    ['behaviour.kinetic-intertitles.shimmer-sweep', 'behaviour',
      'behaviours/kinetic-intertitles/ShimmerSweep',
      ['serif word shimmer', 'kinetic intertitle accent'],
      ['typed pink-white gradient', 'authored sweep window', 'glow stack']],
    ['behaviour.kinetic-intertitles.split-word-cadence', 'behaviour',
      'behaviours/kinetic-intertitles/SplitWordCadence',
      ['split-serif word entrance', 'staggered intertitle phrase'],
      ['per-word spring stagger', 'normalized hold', 'coordinated fade']],
    ['unit.kinetic-intertitles.progress-trace', 'unit',
      'units/kinetic-intertitles/SplitSerifIntertitle',
      ['intertitle progress mark', 'serif underline trace'],
      ['transparent projected trace frame', 'owned by SplitSerifIntertitle', 'direct vector path renderer']],
    ['unit.kinetic-intertitles.scanline-impact', 'unit',
      'units/kinetic-intertitles/ScanlineImpactCaption',
      ['Impact scanline caption', 'condensed kinetic title'],
      ['runtime character row', 'Impact/Anton/Bebas hierarchy', 'typed scanline field']],
    ['unit.kinetic-intertitles.split-serif', 'unit',
      'units/kinetic-intertitles/SplitSerifIntertitle',
      ['split-serif intertitle', 'editorial phrase card'],
      ['runtime word tokens', 'Georgia italic role', 'vector progress trace']],
  ]),

  ...familyMemories('media-montage', [
    ['behaviour.media-montage.black-stutter-reveal', 'behaviour',
      'behaviours/media-montage/BlackStutterReveal',
      ['video handoff blackout', 'first-clip stutter'],
      ['authored black-frame schedule', 'clip-aware reveal cadence']],
    ['behaviour.media-montage.cut-flash-envelope', 'behaviour',
      'behaviours/media-montage/CutFlashEnvelope',
      ['montage cut flash', 'video-segment handoff'],
      ['three-frame exposure hit', 'segment-aware opacity law']],
    ['behaviour.media-montage.first-clip-grade-reveal', 'behaviour',
      'behaviours/media-montage/FirstClipGradeReveal',
      ['opening video grade', 'montage first-shot reveal'],
      ['ordered grade release', 'first-clip vignette envelope']],
    ['behaviour.media-montage.flash-cut-motion', 'behaviour',
      'behaviours/media-montage/FlashCutMotion',
      ['variable-speed video montage', 'flash-cut camera reframe'],
      ['authored segment rates', 'per-segment crop motion', 'cut exposure timing']],
    ['behaviour.media-montage.image-strobe-cuts', 'behaviour',
      'behaviours/media-montage/ImageStrobeCuts',
      ['beat-synced image strobe', 'rapid image selector'],
      ['two-frame source cuts', 'spring image hit', 'twelve-slot schedule']],
    ['behaviour.media-montage.vignette-release', 'behaviour',
      'behaviours/media-montage/VignetteRelease',
      ['opening montage vignette', 'first-shot grade release'],
      ['authored 53-frame window', 'coordinated vignette opacity']],
    ['unit.media-montage.flash-cut-segment', 'unit',
      'units/media-montage/FlashCutSegment',
      ['variable-rate video segment', 'flash-cut montage shot'],
      ['semantic segment identity', 'source offset and playback rate', 'camera crop stage']],
    ['unit.media-montage.cut-flash-plate', 'unit',
      'units/media-montage/FlashCutSegment',
      ['video-segment exposure hit', 'flash-cut handoff'],
      ['semantic flash owner', 'three-frame authored envelope', 'segment-local presence']],
    ['unit.media-montage.flash-cut-vignette', 'unit',
      'units/media-montage/FlashCutVideoMontage',
      ['flash-cut edge vignette', 'multi-segment montage finish'],
      ['full-frame typed radial field', 'transparent centre', 'authored 45% black edge']],
    ['unit.media-montage.flash-cut-video', 'unit',
      'units/media-montage/FlashCutVideoMontage',
      ['multi-segment flash montage', 'speed-ramped video sequence'],
      ['nine authored boundaries', 'typed video backend', 'white-flash handoff']],
    ['unit.media-montage.premounted-shot', 'unit',
      'units/media-montage/PremountedMediaShot',
      ['buffer-safe media cut', 'premounted montage segment'],
      ['typed premount window', 'explicit video backend', 'source-offset ownership']],
    ['unit.media-montage.source-offset-video', 'unit',
      'units/media-montage/SourceOffsetVideoMontage',
      ['source-offset video sequence', 'long-form clip handoff'],
      ['four authored clip boundaries', 'per-shot start offsets', 'volume schedule']],
    ['unit.media-montage.strobe-image', 'unit',
      'units/media-montage/StrobeImageMontage',
      ['rapid image selector', 'beat strobe montage'],
      ['twelve runtime media slots', 'hard two-frame selection', 'radial vignette']],
    ['unit.media-montage.vignette-reveal-clip', 'unit',
      'units/media-montage/VignetteRevealClip',
      ['opening video clip', 'graded montage reveal'],
      ['black stutter field', 'grade and vignette channels', 'premounted video shot']],
    ['unit.media-montage.first-clip-black-stutter', 'unit',
      'units/media-montage/VignetteRevealClip',
      ['opening clip blackout', 'video stutter reveal'],
      ['semantic black-field owner', 'authored first-frame schedule', 'clip-local presence']],
    ['unit.media-montage.first-clip-vignette', 'unit',
      'units/media-montage/VignetteRevealClip',
      ['opening clip vignette', 'graded video reveal'],
      ['semantic vignette owner', 'authored 53-frame release', 'radial edge treatment']],
  ]),

  ...familyMemories('micro-flash', [
    ['behaviour.micro-flash.pulse', 'behaviour',
      'behaviours/micro-flash/FlashPulse',
      ['seven-frame edit flash', 'micro exposure card'],
      ['authored rise at 30 percent', 'last-frame endpoint variants']],
    ['unit.micro-flash.card', 'unit',
      'units/micro-flash/MicroFlashCard',
      ['timeline exposure hit', 'full-frame flash card'],
      ['white-family authored colors', 'seven-frame full-field topology']],
  ]),

  ...familyMemories('neon-heart-pop', [
    ['behaviour.neon-heart-pop.chroma-stack-pop', 'behaviour',
      'behaviours/neon-heart-pop/ChromaStackPop',
      ['chromatic word stack entrance', 'neon name hit'],
      ['zero-to-overshoot scale', 'cyan/red ghost alignment', 'out-cubic settle']],
    ['behaviour.neon-heart-pop.dual-line-glitch-cadence', 'behaviour',
      'behaviours/neon-heart-pop/DualLineGlitchCadence',
      ['dual-line neon title', 'horizontal glitch handoff'],
      ['opposed line travel', 'authored sine jitter', 'rule expansion']],
    ['behaviour.neon-heart-pop.five-hit-camera-shake', 'behaviour',
      'behaviours/neon-heart-pop/FiveHitPhotoCadence',
      ['five-photo impact sequence', 'shared hit-camera motion'],
      ['five authored impact windows', 'directional camera shake', 'zero-state rollback']],
    ['behaviour.neon-heart-pop.five-hit-exposure-burst', 'behaviour',
      'behaviours/neon-heart-pop/FiveHitPhotoCadence',
      ['five-photo exposure hit', 'slam-sequence flash'],
      ['five authored exposure windows', 'conditional semantic presence']],
    ['behaviour.neon-heart-pop.five-hit-photo-slam', 'behaviour',
      'behaviours/neon-heart-pop/FiveHitPhotoCadence',
      ['individual photo-card impact', 'five-beat media slam'],
      ['per-index entrance direction', '100ms shake', '150ms slam settle']],
    ['behaviour.neon-heart-pop.five-hit-title-slam', 'behaviour',
      'behaviours/neon-heart-pop/FiveHitPhotoCadence',
      ['late neon nameplate hit', 'photo-sequence title landing'],
      ['authored 750ms cue', '80ms scale-three landing', 'chromatic title shadow']],
    ['behaviour.neon-heart-pop.flip-title-reveal', 'behaviour',
      'behaviours/neon-heart-pop/FlipTitleReveal',
      ['3D neon title flip', 'hot-pink title landing'],
      ['rotateX and translateZ entrance', 'authored cubic landing', 'sine wobble']],
    ['behaviour.neon-heart-pop.heart-constellation-twinkle', 'behaviour',
      'behaviours/neon-heart-pop/SpinningHeartCadence',
      ['spinning-heart star field', 'neon constellation twinkle'],
      ['five authored phase offsets', 'semantic star cadence', 'hot-pink glow']],
    ['behaviour.neon-heart-pop.orbit-caption-reveal', 'behaviour',
      'behaviours/neon-heart-pop/OrbitHeartCadence',
      ['orbit-heart caption', 'late neon title cue'],
      ['350–550ms reveal window', 'two-role caption lockup']],
    ['behaviour.neon-heart-pop.orbit-heart-burst', 'behaviour',
      'behaviours/neon-heart-pop/OrbitHeartCadence',
      ['orbiting heart entrance', 'neon heart hero'],
      ['authored spring burst', 'one-turn rotateY', 'perspective settle']],
    ['behaviour.neon-heart-pop.orbit-particle-cadence', 'behaviour',
      'behaviours/neon-heart-pop/OrbitHeartCadence',
      ['heart orbital light', 'four-particle neon orbit'],
      ['radius-140 orbit', 'two cycles per second', 'quadrature phase offsets']],
    ['behaviour.neon-heart-pop.spinning-heart-burst', 'behaviour',
      'behaviours/neon-heart-pop/SpinningHeartCadence',
      ['spinning vector heart', 'neon heart reveal'],
      ['18-frame authored spring', 'rotateY turn', 'perspective heart glow']],
    ['behaviour.neon-heart-pop.split-nameplate-cadence', 'behaviour',
      'behaviours/neon-heart-pop/SplitNameplateCadence',
      ['split neon nameplate', 'opposed-line title reveal'],
      ['semantic role-specific cadence', 'label and particle timing', 'one-hertz pulse']],
    ['unit.neon-heart-pop.chroma-word-stack', 'unit',
      'units/neon-heart-pop/NeonChromaWordStack',
      ['stacked chromatic name', 'fast neon title'],
      ['three runtime text roles', 'cyan/red ghost copies', 'hot-pink rule']],
    ['unit.neon-heart-pop.dual-line-glitch', 'unit',
      'units/neon-heart-pop/NeonDualLineGlitch',
      ['dual-line glitch nameplate', 'neon versus title'],
      ['semantic line owners', 'cyan/red ghost copies', 'expanding hot-pink rule']],
    ['unit.neon-heart-pop.five-hit-photo-nameplate', 'unit',
      'units/neon-heart-pop/NeonFiveHitPhotoNameplate',
      ['five-photo hit sequence', 'late chromatic nameplate'],
      ['five runtime Image cards', 'shared camera stage', 'semantic exposure channel']],
    ['unit.neon-heart-pop.flip-title', 'unit',
      'units/neon-heart-pop/NeonFlipTitle',
      ['3D neon title', 'perspective name flip'],
      ['500px perspective field', 'pink blur ghost', 'white-to-pink clipped gradient']],
    ['unit.neon-heart-pop.orbit-heart', 'unit',
      'units/neon-heart-pop/NeonOrbitHeart',
      ['orbiting heart lockup', 'neon caption hero'],
      ['CSS-built hot-pink heart', 'four orbital lights', 'Bebas/Caveat caption roles']],
    ['unit.neon-heart-pop.spinning-heart', 'unit',
      'units/neon-heart-pop/NeonSpinningHeart',
      ['spinning vector heart', 'neon constellation hero'],
      ['authored vector heart', 'five twinkle points', '600px perspective field']],
    ['unit.neon-heart-pop.split-nameplate', 'unit',
      'units/neon-heart-pop/NeonSplitNameplate',
      ['split neon nameplate', 'opposed-line title'],
      ['runtime primary/accent/label roles', 'gold particles', 'hot-pink divider']],
  ]),

  ...familyMemories('photo-glitch', [
    ['behaviour.photo-glitch.beat-photo-cadence', 'behaviour',
      'behaviours/photo-glitch/BeatPhotoCadence',
      ['beat-synced photo glitch', 'rapid RGB media hit'],
      ['authored beat period', 'spring photo impact', 'four glitch variants']],
    ['behaviour.photo-glitch.beat-vignette-flicker', 'behaviour',
      'behaviours/photo-glitch/BeatVignetteFlicker',
      ['beat-photo vignette', 'glitch-field exposure pulse'],
      ['deterministic vignette flicker', 'beat-local exposure cadence']],
    ['behaviour.photo-glitch.masked-panel-reveal', 'behaviour',
      'behaviours/photo-glitch/MaskedPanelSpringReveal',
      ['polygon photo panel entrance', 'masked triptych reveal'],
      ['panel-specific spring', 'delayed opacity window', 'clip-aware pose']],
    ['behaviour.photo-glitch.panel-ken-burns', 'behaviour',
      'behaviours/photo-glitch/PanelKenBurnsDrift',
      ['masked photo drift', 'triptych Ken Burns motion'],
      ['full-duration pan and scale', 'panel-index direction', 'crop-safe motion']],
    ['behaviour.photo-glitch.perspective-card-drop', 'behaviour',
      'behaviours/photo-glitch/PerspectiveCardDrop',
      ['perspective photo card', 'four-card depth stack'],
      ['authored per-card delay', 'drop and settle springs', 'ordered rotateX/Y/Z']],
    ['behaviour.photo-glitch.rgb-beat-glitch', 'behaviour',
      'behaviours/photo-glitch/RgbBeatGlitch',
      ['RGB split photo hit', 'beat-local scan distortion'],
      ['four-frame RGB burst', 'authored jitter phases', 'source-slot cadence']],
    ['behaviour.photo-glitch.triptych-exit', 'behaviour',
      'behaviours/photo-glitch/TriptychExitFade',
      ['masked triptych exit', 'photo-panel handoff'],
      ['last-24-frame cubic fade', 'coordinated panel exit']],
    ['unit.photo-glitch.beat-photo', 'unit',
      'units/photo-glitch/BeatGlitchPhoto',
      ['beat-driven photo plate', 'RGB glitch media card'],
      ['eleven runtime image slots', 'RGB ghost layers', 'three-pixel scanlines']],
    ['unit.photo-glitch.beat-media', 'unit',
      'units/photo-glitch/RgbGlitchStage',
      ['beat-cut runtime image', 'chromatic source carrier'],
      ['closed beat identity', 'beat-local frame state', 'authored variant state']],
    ['unit.photo-glitch.beat-exposure-vignette', 'unit',
      'units/photo-glitch/BeatGlitchPhoto',
      ['beat-photo exposure field', 'glitch vignette treatment'],
      ['semantic exposure/vignette owner', 'authored beat-local flicker', 'radial edge treatment']],
    ['unit.photo-glitch.masked-panel', 'unit',
      'units/photo-glitch/MaskedPhotoPanel',
      ['polygon photo panel', 'masked editorial crop'],
      ['typed polygon clip', 'runtime Image carrier', 'semantic panel identity']],
    ['unit.photo-glitch.masked-panel-media', 'unit',
      'units/photo-glitch/MaskedPhotoPanel',
      ['masked-panel runtime image', 'triptych camera carrier'],
      ['closed panel identity', 'authored panel index', 'camera progress state']],
    ['unit.photo-glitch.masked-triptych', 'unit',
      'units/photo-glitch/MaskedPanelTriptych',
      ['three-panel masked photo', 'editorial triptych'],
      ['three authored polygons', 'staggered panels', 'shared exit stage']],
    ['unit.photo-glitch.perspective-card', 'unit',
      'units/photo-glitch/PerspectivePhotoCard',
      ['3D photo card', 'perspective media stack'],
      ['runtime Image crop', 'semantic card index', 'preserve-3d pose']],
    ['unit.photo-glitch.perspective-stack', 'unit',
      'units/photo-glitch/PerspectivePhotoStack',
      ['four-card photo depth stack', 'perspective collage'],
      ['1400px perspective', 'four authored card poses', 'depth-order topology']],
    ['unit.photo-glitch.polygon-clip-content', 'unit',
      'units/photo-glitch/PolygonClipContent',
      ['typed polygon content crop', 'masked photo region'],
      ['renderer-neutral clip geometry', 'semantic clipped-content owner']],
    ['unit.photo-glitch.rgb-stage', 'unit',
      'units/photo-glitch/RgbGlitchStage',
      ['chromatic photo stage', 'RGB beat distortion'],
      ['red/cyan ghost topology', 'scanline surface', 'vignette channel']],
  ]),

  ...familyMemories('rapid-photo', [
    ['behaviour.rapid-photo.cut', 'behaviour',
      'behaviours/rapid-photo/RapidPhotoCut',
      ['single-shot rapid reframe', 'graded photo cut'],
      ['six authored camera laws', 'ordered grade filters', 'exact Remotion easing parity']],
    ['unit.rapid-photo.plate', 'unit',
      'units/rapid-photo/RapidPhotoPlate',
      ['rapid graded photo', 'micro camera reframe'],
      ['runtime full-frame Image', 'semantic motion owner', 'radial vignette topology']],
  ]),

  ...familyMemories('sculptural-3d', [
    ['behaviour.sculptural-3d.heart-pulse-orbit', 'behaviour',
      'behaviours/sculptural-3d/HeartPulseOrbit',
      ['sculptural heart reveal', 'floating heart hero'],
      ['authored beat spring', 'whole-scene pose and aura', 'light and orbit state']],
    ['behaviour.sculptural-3d.ink-tendril-reveal', 'behaviour',
      'behaviours/sculptural-3d/InkTendrilReveal',
      ['procedural ink field', 'tendril field reveal'],
      ['duration-normalized state', 'in-out sine reveal', 'progress/time/aspect contract']],
    ['behaviour.sculptural-3d.scissor-snap-flight', 'behaviour',
      'behaviours/sculptural-3d/ScissorSnapFlight',
      ['sculptural scissors entrance', 'sculptural logo lockup'],
      ['two authored springs', 'blade snap and flight', 'whole-scene pose state']],
    ['behaviour.sculptural-3d.scissors-stage-cadence', 'behaviour',
      'behaviours/sculptural-3d/ScissorsStageCadence',
      ['sculptural scissors full-stage cadence', '3D title-and-light lockup'],
      ['coordinated glow/copy/flash/fade', 'closed semantic projection roles', 'authored spring and pulse windows']],
    ['unit.sculptural-3d.heart-hero', 'unit',
      'units/sculptural-3d/SculpturalHeartHero',
      ['heart centerpiece', 'neon sculptural hero'],
      ['native host capability', 'centered heart/aura semantics', '80-ember orbit slot']],
    ['unit.sculptural-3d.ink-tendril-plane', 'unit',
      'units/sculptural-3d/InkTendrilPlane',
      ['procedural ink field', 'tendril transition plane'],
      ['native host capability', 'full-frame reveal semantics', 'progress/time/aspect state']],
    ['unit.sculptural-3d.scissors-hero', 'unit',
      'units/sculptural-3d/SculpturalScissorsHero',
      ['sculptural scissors logo', 'metallic sculptural title'],
      ['native host capability', 'impact/minimal variants', 'whole-scene motion state']],
    ['unit.sculptural-3d.scissors-stage', 'unit',
      'units/sculptural-3d/SculpturalScissorsStage',
      ['full-frame sculptural scissors title', 'sculptural logo with runtime copy'],
      ['runtime four-slot copy', 'typed glow/vignette/scanline topology', 'Bebas/Montserrat/Barlow roles']],
  ]),

  ...familyMemories('turbulent-emulsion', [
    ['behaviour.turbulent-emulsion.drift', 'behaviour',
      'behaviours/turbulent-emulsion/EmulsionDrift',
      ['analog SVG emulsion', 'turbulent media surface'],
      ['typed turbulence evolution', 'displacement and colour-matrix coordination']],
    ['behaviour.turbulent-emulsion.flicker', 'behaviour',
      'behaviours/turbulent-emulsion/EmulsionFlicker',
      ['film-grain exposure flicker', 'analog title distress'],
      ['deterministic frame-modulo phases', 'opacity and filter-graph cadence']],
    ['unit.turbulent-emulsion.handwritten-title', 'unit',
      'units/turbulent-emulsion/HandwrittenEmulsionTitle',
      ['handwritten analog title', 'distressed marker intertitle'],
      ['runtime Text role', 'Estonia script', 'turbulent SVG treatment']],
    ['unit.turbulent-emulsion.overlay', 'unit',
      'units/turbulent-emulsion/EmulsionOverlay',
      ['film-emulsion overlay', 'turbulent media distress'],
      ['typed SVG filter graph', 'turbulence and displacement', 'blend-ready full-frame surface']],
    ['unit.turbulent-emulsion.surface', 'unit',
      'units/turbulent-emulsion/EmulsionOverlay',
      ['authored emulsion scene surface', 'turbulent full-frame backdrop'],
      ['authored per-variant scene and motion', 'owned by EmulsionOverlay', 'direct declarative SVG renderer']],
  ]),

  memory('behaviour.outlined-word-card.word-cue-state', 'behaviour', 'outlined-word-card',
    '@cut3/agent-memory/behaviours/outlined-word-card/WordCueState',
    ['hard-cued social word groups', 'outlined kinetic word cards'],
    ['one-to-four word slots', 'length-fitted display type', 'true black text stroke', 'hard cue persistence']),
  memory('unit.outlined-word-card.word-group', 'unit', 'outlined-word-card',
    '@cut3/agent-memory/units/outlined-word-card/OutlinedWordGroup',
    ['outlined word sequence', 'hard-switched phrase card'],
    ['full black field', 'runtime word cardinality', 'white fill', 'heavy outlined type']),

  ...familyMemories('conn-check-88bf76acecbb', [
    ['unit.conn-check-88bf76acecbb.marker', 'unit',
      'units/conn-check-88bf76acecbb/ConnCheckUnit88bf76acecbb',
      ['infrastructure connectivity test marker', 'conn-check-88bf76acecbb unit'],
      ['CONN_CHECK_MARKER_88BF76ACECBB export', 'plain monochrome plate', 'Text content child']],
    ['behaviour.conn-check-88bf76acecbb.marker', 'behaviour',
      'behaviours/conn-check-88bf76acecbb/ConnCheckSettle88bf76acecbb',
      ['infrastructure connectivity test entrance', 'conn-check-88bf76acecbb settle'],
      ['scale-and-fade entrance', 'easeOutCubic 18-frame settle', 'opacity ramp']],
  ]),

];

export const memoryCatalog = Object.freeze(entries);

export function findMemories({ style, purpose, type } = {}) {
  return memoryCatalog.filter((entry) => (
    (style === undefined || entry.style === style)
    && (type === undefined || entry.type === type)
    && (purpose === undefined || entry.useWhen.includes(purpose))
  ));
}

function memory(id, type, style, importPath, useWhen, preserves) {
  return Object.freeze({
    id,
    import: importPath,
    preserves: Object.freeze(preserves),
    style,
    type,
    useWhen: Object.freeze(useWhen),
  });
}

function familyMemories(style, definitions) {
  return definitions.map(([id, type, importPath, useWhen, preserves]) => memory(
    id,
    type,
    style,
    `@cut3/agent-memory/${importPath}`,
    useWhen,
    preserves,
  ));
}
